name: ofline_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
#  audioplayers: ^6.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  share_plus: ^9.0.0
  url_launcher: ^6.1.8
  animated_text_kit: ^4.2.2
  receive_sharing_intent: ^1.8.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0
  flutter_riverpod: ^2.5.1
  location: ^6.0.2
  intl: ^0.19.0
  google_ml_kit: ^0.18.0
  google_mlkit_text_recognition: ^0.13.0
  google_maps_flutter: ^2.7.0
  firebase_storage: ^12.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true



  assets:
    - images/Google icon.png
    - images/pix.jpg
    - images/coffee.jpg
    - images/bag.jpg
    - images/mall.jpg
    - images/burger.jpg
    - images/burger-king-1.jpg
    - images/burger-king.jpg
    - images/burger-king-2.jpg
#    - assets/note1.wav.mp3
#    - assets/note2.wav.mp3
#    - assets/note3.wav.mp3

  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
