// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuP-CAi69WCr55qVCTlCmKhFRbgL4pDp0',
    appId: '1:928193570216:android:af732b607d3f6a66d3299d',
    messagingSenderId: '928193570216',
    projectId: 'ofline-dev',
    storageBucket: 'ofline-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX23FD8J08Zw3rGGpOf2qZ3cabYu3RyEg',
    appId: '1:928193570216:ios:35fc9157f821fb5ed3299d',
    messagingSenderId: '928193570216',
    projectId: 'ofline-dev',
    storageBucket: 'ofline-dev.appspot.com',
    iosClientId: '928193570216-2qiot7ha45ll29h7ek64ep97sv384alv.apps.googleusercontent.com',
    iosBundleId: 'com.ofline.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX23FD8J08Zw3rGGpOf2qZ3cabYu3RyEg',
    appId: '1:928193570216:ios:35fc9157f821fb5ed3299d',
    messagingSenderId: '928193570216',
    projectId: 'ofline-dev',
    storageBucket: 'ofline-dev.appspot.com',
    iosClientId: '928193570216-2qiot7ha45ll29h7ek64ep97sv384alv.apps.googleusercontent.com',
    iosBundleId: 'com.ofline.app',
  );
}
